### PR TITLE
(Fix) Credit note for an invoice in the invoices registry

### LINKED ISSUE #159: (bug) No way to find the Credit Note for an Invoice from the Invoice Registry
The invoice registry colors reversed (via credit note) records red.  Unfortunately, there is no way to find the associated credit note!  Even the voucher registry does not have a way to find the correct credit note.

The following changes need to be made:
 1. _At minimum_, the Voucher description must include the invoice reference.
 2. Allow the invoice registry to directly link the credit note (using [dropdowns #52](https://github.com/Vanga-Hospital/bhima-2.X/issues/52)).

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fix the issue #159 

- [x] Signal in the invoice that it is credit noted

creditnote

creditnote

creditnote

creditnote

Close #159

### CODE REVIEW

File: client/src/partials/patient_invoice/registry/modalCreditNote.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ function ModalCreditNoteController(Instance, Invoices, data, Vouchers, Notify) {
 
   vm.creditNote.uuid = data.invoice.uuid;
   vm.patientInvoice = data.invoice;
+  vm.creditNote.description = data.invoice.reference + '/';
```
Comment (sfount) [inline client/src/partials/patient_invoice/registry/modalCreditNote.js]: If it is possible I would add this invoice reference into the automatically generated part of the credit note description. 

It could then be formatted like this: `This is a credit note for an invoice (IV.HEV.14) ...` for example.

File: server/controllers/finance/patientInvoice.js [hunk 2]
```diff
@@ -308,3 +313,19 @@ function search(req, res, next) {
...
+function lookupInvoiceCreditNote(invoiceUuid) {
+  let buid = db.bid(invoiceUuid);
+  const sql = `
+    SELECT BUID(v.uuid) AS uuid, v.date, CONCAT_WS('.', '${identifiers.VOUCHER.key}', p.abbr, v.reference) AS reference, 
+      v.currency_id, v.amount, v.description, v.reference_uuid, u.display_name 
+    FROM voucher v 
+    JOIN project p ON p.id = v.project_id 
+    JOIN user u ON u.id = v.user_id 
+    JOIN invoice i ON i.uuid = v.reference_uuid
+    WHERE v.type_id = ${CREDIT_NOTE_ID} AND v.reference_uuid = ?`;
```
Comment (jniles) [inline server/controllers/finance/patientInvoice.js]: :+1:

File: client/src/partials/patient_invoice/registry/templates/creditNote.action.tmpl.html [hunk 3]
```diff
@@ -1,5 +1,15 @@
-<div class="ui-grid-cell-contents text-action" ng-click="grid.appScope.creditNote(row.entity)">
-  <a href id="{{ ::row.entity.reference }}" class="text-danger">
-    <i class="fa fa-clone"></i> <span translate>TABLE.COLUMNS.CREDIT_NOTE</span>
-  </a>
+<div class="ui-grid-cell-contents">
+  <span uib-dropdown dropdown-append-to-body>
+
+    <span uib-dropdown-toggle class="text-action">
+      Actions
```
Comment (jniles) [inline client/src/partials/patient_invoice/registry/templates/creditNote.action.tmpl.html]: In the future, this should be a `<a>` anchor tag so that it stands out from the other text ... a caret isn't visible enough for users with poor eyesight.

File: server/controllers/finance/reports/invoices/receipt.handlebars [hunk 4]
```diff
@@ -5,6 +5,13 @@
   <header>
     <!-- headings  -->
     <div class="row">
+      {{#if isCreditNoted}}
+        <div class="text-center" style="position: absolute; border: 5px solid #ccc; -webkit-transform: rotate(10deg); transform: rotate(10deg); left: 35%; top: 20px;">
```
Comment (jniles) [inline server/controllers/finance/reports/invoices/receipt.handlebars]: This is cool :)

File: server/controllers/finance/reports/invoices/index.js [hunk 5]
```diff
@@ -145,6 +147,77 @@ function receipt(req, res, next) {
...
+  } catch (e) {
+    return next(e);
+  }
+
+  Invoices.lookupInvoice(invoiceUuid)
+    .then(reportResult => {
+      let recipientUuid = reportResult.patient_uuid;
+      _.extend(invoiceResponse, reportResult);
+
+      let queries = {
```
Comment (jniles) [inline server/controllers/finance/reports/invoices/index.js]: Can you put the `Invoices.lookupInvoiceCreditNote(invoiceUuid);` up here?  That way, you reduce the number of `.then()` calls and can do some of the work in parallel?

File: server/controllers/finance/reports/invoices/receipt.handlebars [hunk 6]
```diff
@@ -5,6 +5,13 @@
...
+          <span style="font-size: 24px; color: #ccc;">
```
Comment (jniles) [inline server/controllers/finance/reports/invoices/receipt.handlebars]: I propose you make this `text-danger` so that it is really obvious.

File: client/src/partials/patient_invoice/registry/registry.js [hunk 7]
```diff
@@ -110,6 +110,9 @@ function InvoiceRegistryController(Invoices, bhConstants, Notify, Session, util,
       invoices.forEach(function (invoice) {
         invoice._backgroundColor =
           (invoice.type_id === bhConstants.transactionType.CREDIT_NOTE) ?  reversedBackgroundColor : regularBackgroundColor;
+
+        invoice._is_cancelled =
```
Comment (jniles) [inline client/src/partials/patient_invoice/registry/registry.js]: Whenever you do
```js
var x = (value === otherValue) ? true : false;
```
you can just right
```js
var x = (value === otherValue);
```
And save a single operation.

File: client/src/partials/patient_invoice/registry/templates/creditNote.action.tmpl.html (hunk 3 above)
Comment (sfount) [inline client/src/partials/patient_invoice/registry/templates/creditNote.action.tmpl.html]: This should also be run through the `translate` directive.

**Comment by sfount** [comment]
@mbayopanda This PR breaks on an end to end test for viewing the proof of an invoice - this will have to be updated to use the new dropdown that you have implemented. 

If the can be updated by noon this can be merged for use today, great work!

File: server/controllers/finance/reports/invoices/receipt.handlebars (hunk 6 above)
Comment (mbayopanda) [inline server/controllers/finance/reports/invoices/receipt.handlebars]: 👍

**Comment by jniles** [comment]
Looks like the test pass!  Merging ...
